// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ibps.demo;

import com.ibps.demo.Examl;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Examl_Roo_Configurable {
    
    declare @type: Examl: @Configurable;
    
}
